web:
  build: .
  command: 'bash -c ''vendor/bin/heroku-php-nginx'''
  working_dir: /app/user
  environment:
    PORT: 8080
    APP_NAME: 192
    APP_HOST_SUFFIX: .168.99.100:8080
    DATABASE_URL: 'postgres://postgres:@herokuPostgresql:5432/postgres'
  ports:
    - '8080:8080'
  links:
    - herokuPostgresql
  volumes:
    - '.:/app/user'
worker:
  build: .
  command: 'bash -c ''php ./update_daemon2.php'''
  working_dir: /app/user
  environment:
    APP_NAME: ttrss
    APP_HOST_SUFFIX: .dev
    DATABASE_URL: 'postgres://postgres:@herokuPostgresql:5432/postgres'
  links:
    - herokuPostgresql
  volumes:
    - '.:/app/user'
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    APP_NAME: ttrss
    APP_HOST_SUFFIX: .dev
    DATABASE_URL: 'postgres://postgres:@herokuPostgresql:5432/postgres'
  links:
    - herokuPostgresql
  volumes:
    - '.:/app/user'
herokuPostgresql:
  image: postgres
  ports:
    - '5432:5432'
