web:
  build: .
  command: 'bash -c ''vendor/bin/heroku-php-nginx'''
  working_dir: /app/user
  environment:
    PORT: 5000
    APP_NAME: ttrss
    APP_HOST_SUFFIX: .dev
    DATABASE_URL: 'postgres://postgres:@herokuPostgresql:5432/postgres'
  ports:
    - '5000:5000'
  links:
    - herokuPostgresql
  volumes:
    - '.:/app/user'
worker:
  build: .
  command: 'php ./update_daemon2.php'
  user: appuser
  working_dir: /app/user
  environment:
    APP_NAME: ttrss
    APP_HOST_SUFFIX: .dev
    DATABASE_URL: 'postgres://postgres:@herokuPostgresql:5432/postgres'
  links:
    - herokuPostgresql
  volumes:
    - '.:/app/user'
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    APP_NAME: ttrss
    APP_HOST_SUFFIX: .dev
    DATABASE_URL: 'postgres://postgres:@herokuPostgresql:5432/postgres'
  links:
    - herokuPostgresql
  volumes:
    - '.:/app/user'
herokuPostgresql:
  image: postgres:latest
  ports:
    - '5432:5432'
