FROM php:7-cli

RUN apt-get update

RUN docker-php-ext-install pcntl && \
    docker-php-ext-install mbstring

RUN apt-get -y install libzip4 libzip-dev

RUN docker-php-ext-install zip

RUN curl -sS https://getcomposer.org/installer -o composer-setup.php && \
    php composer-setup.php --install-dir=/usr/local/bin --filename=composer && \
    rm composer-setup.php
